from app.execution.models import ValidatorDefinition

VALIDATORS: dict[str, ValidatorDefinition] = {
    "python.syntax": ValidatorDefinition(
        id="python.syntax",
        executable="python",
        argument_builder="py_compile",
        executes_repository_code=False,
        requires_network=False,
        default_timeout_seconds=30,
        default_memory_limit_mb=512,
        allowed_working_directories=["."],
    ),
    "python.ruff": ValidatorDefinition(
        id="python.ruff",
        executable="ruff",
        argument_builder="ruff_check",
        executes_repository_code=False,
        requires_network=False,
        default_timeout_seconds=60,
        default_memory_limit_mb=512,
        allowed_working_directories=["."],
    ),
    "python.pytest": ValidatorDefinition(
        id="python.pytest",
        executable="pytest",
        argument_builder="pytest_args",
        executes_repository_code=True,
        requires_network=False,
        default_timeout_seconds=120,
        default_memory_limit_mb=1024,
        allowed_working_directories=["."],
    ),
    "typescript.tsc": ValidatorDefinition(
        id="typescript.tsc",
        executable="tsc",
        argument_builder="tsc_no_emit",
        executes_repository_code=False,
        requires_network=False,
        default_timeout_seconds=90,
        default_memory_limit_mb=1024,
        allowed_working_directories=["."],
    ),
    "javascript.eslint": ValidatorDefinition(
        id="javascript.eslint",
        executable="eslint",
        argument_builder="eslint_check",
        executes_repository_code=False,
        requires_network=False,
        default_timeout_seconds=60,
        default_memory_limit_mb=512,
        allowed_working_directories=["."],
    ),
    "javascript.build": ValidatorDefinition(
        id="javascript.build",
        executable="npm",
        argument_builder="npm_build",
        executes_repository_code=True,
        requires_network=False,
        default_timeout_seconds=180,
        default_memory_limit_mb=2048,
        allowed_working_directories=["."],
    ),
    "docker.compose_config": ValidatorDefinition(
        id="docker.compose_config",
        executable="docker",
        argument_builder="compose_config",
        executes_repository_code=False,
        requires_network=False,
        default_timeout_seconds=30,
        default_memory_limit_mb=512,
        allowed_working_directories=["."],
    ),
    "java.maven_test": ValidatorDefinition(
        id="java.maven_test",
        executable="mvn",
        argument_builder="mvn_test",
        executes_repository_code=True,
        requires_network=False,
        default_timeout_seconds=180,
        default_memory_limit_mb=2048,
        allowed_working_directories=["."],
    ),
    "cpp.cmake_build": ValidatorDefinition(
        id="cpp.cmake_build",
        executable="cmake",
        argument_builder="cmake_build",
        executes_repository_code=True,
        requires_network=False,
        default_timeout_seconds=180,
        default_memory_limit_mb=2048,
        allowed_working_directories=["."],
    ),
}


def get_validator(validator_id: str) -> ValidatorDefinition | None:
    return VALIDATORS.get(validator_id)
