import ChatInterface from "@/components/chat";
import { Badge } from "@/components/ui/badge";
import { reindexSessionRag } from "@/lib/api";
import { cn } from "@/lib/utils";
import type { EvidenceItem } from "@/types/agent.type";
import type { SingleSessionResponse } from "@/types/session.type";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, AlertTriangle, ArrowUpRight, BookOpen, CheckCircle2, Clock3, Code2, FileCode2, FileSearch, GitBranch, GitCommitHorizontal, GitPullRequest, RefreshCw, ShieldCheck, Workflow } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { toast } from "sonner";
import { getSessionBySlug } from "@/lib/api";

const sections = ["overview", "assistant", "pipelines", "investigation", "knowledge", "code", "changes", "history"] as const;
type Section = typeof sections[number];
const label = (value?: string | null) => value ? value.replaceAll("_", " ") : "Unavailable";
const shortSha = (sha?: string | null) => sha ? sha.slice(0, 12) : "Unavailable";

function PageTitle({ title, description, actions }: { title: string; description: string; actions?: React.ReactNode }) {
  return <header className="flex flex-wrap items-start justify-between gap-4 border-b border-border px-6 py-5"><div><h1 className="text-xl font-semibold tracking-tight">{title}</h1><p className="mt-1 max-w-3xl text-sm leading-6 text-muted-foreground">{description}</p></div>{actions}</header>;
}
function Panel({ title, icon: Icon, children, className }: { title: string; icon?: typeof Activity; children: React.ReactNode; className?: string }) {
  return <section className={cn("rounded-xl border border-border bg-card p-4 shadow-sm", className)}><div className="mb-3 flex items-center gap-2 text-sm font-semibold">{Icon ? <Icon className="size-4 text-primary" /> : null}{title}</div>{children}</section>;
}
function Empty({ children }: { children: React.ReactNode }) { return <p className="rounded-lg border border-dashed border-border bg-muted/25 p-4 text-sm leading-6 text-muted-foreground">{children}</p>; }
function EvidenceCard({ item }: { item: EvidenceItem }) {
  const ci = item.sourceType === "ci_log";
  return <article className="rounded-lg border border-border bg-background p-3"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{ci ? "GitHub Actions" : item.sourceType}</Badge>{item.metadata?.state === "failed_run" ? <Badge variant="secondary">Historical CI evidence</Badge> : null}{item.metadata?.truncated ? <Badge variant="secondary">Excerpt truncated</Badge> : null}</div><p className="mt-2 font-medium">{item.title}</p>{ci ? <p className="mt-1 text-xs text-muted-foreground">{item.metadata?.workflow_name ?? "Workflow"} · {item.metadata?.job_name ?? "job"}{item.metadata?.failed_step ? ` · ${item.metadata.failed_step}` : ""}</p> : null}<p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{item.excerpt}</p><div className="mt-3 flex flex-wrap gap-3 text-xs text-muted-foreground">{item.path ? <span>{item.path}</span> : null}{item.commitSha ? <span className="font-mono">{shortSha(item.commitSha)}</span> : null}{item.metadata?.html_url ? <a className="inline-flex items-center gap-1 text-primary hover:underline" href={item.metadata.html_url} target="_blank" rel="noreferrer">Open in GitHub <ArrowUpRight className="size-3" /></a> : null}</div></article>;
}
function ContextBar({ data }: { data: SingleSessionResponse }) {
  const snapshot = data.commandCenter; const repo = snapshot?.repository;
  return <div className="flex flex-wrap items-center gap-x-5 gap-y-2 border-b border-border bg-background/90 px-6 py-3 text-xs text-muted-foreground"><span className="font-medium text-foreground">{data.session.title ?? data.session.repoName ?? "Operation"}</span><span>{repo?.name ?? data.session.repoName ?? "Repository not connected"}</span><span><GitBranch className="mr-1 inline size-3" />{repo?.branch ?? data.session.branchName ?? data.session.defaultBranch ?? "branch unavailable"}</span><span className="font-mono">SHA {shortSha(repo?.commit_sha)}</span><Badge variant="outline" className={data.session.indexStatus === "ready" ? "border-emerald-500/40 text-emerald-700 dark:text-emerald-300" : ""}>Index {data.session.indexStatus ?? "not started"}</Badge></div>;
}
function Overview({ data }: { data: SingleSessionResponse }) {
 const s = data.commandCenter; const ci = s?.ci; const approval = s?.approvals?.find((a) => a.status === "pending");
 return <><PageTitle title="Overview" description="The current operational picture for this repository, backed by the latest persisted investigation." /><div className="grid gap-4 p-6 xl:grid-cols-3"><Panel title="Repository health" icon={CheckCircle2}><dl className="space-y-2 text-sm"><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Repository</dt><dd className="truncate">{s?.repository?.name ?? data.session.repoName ?? "Not connected"}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Current SHA</dt><dd className="font-mono">{shortSha(s?.repository?.commit_sha)}</dd></div><div className="flex justify-between gap-3"><dt className="text-muted-foreground">Index</dt><dd>{data.session.indexStatus ?? "not started"}</dd></div></dl></Panel><Panel title="Latest investigation" icon={FileSearch}>{s?.investigation ? <><p className="text-sm font-medium">{label(s.investigation.status)}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{s.investigation.summary}</p><Link className="mt-3 inline-block text-sm text-primary hover:underline" to={`/session/${data.session.slugId}/investigation`}>Review evidence and hypotheses</Link></> : <Empty>Run an investigation to create a traceable diagnosis.</Empty>}</Panel><Panel title="Pending approval" icon={ShieldCheck}>{approval ? <><p className="text-sm font-medium">{approval.summary}</p><p className="mt-2 text-sm text-muted-foreground">Risk: {approval.riskLevel ?? "approval required"}</p><Link className="mt-3 inline-block text-sm text-primary hover:underline" to={`/session/${data.session.slugId}/changes`}>Review exact change</Link></> : <Empty>No approval is pending. Read-only investigation never needs approval.</Empty>}</Panel><Panel title="CI signal" icon={Workflow} className="xl:col-span-2">{ci ? <div className="grid gap-2 text-sm md:grid-cols-2"><p><span className="text-muted-foreground">Workflow:</span> {ci.workflow_name ?? "Unknown"} · run #{ci.run_id}</p><p><span className="text-muted-foreground">Run SHA:</span> <span className="font-mono">{shortSha(ci.head_sha)}</span></p><p><span className="text-muted-foreground">Failed jobs:</span> {ci.failed_jobs.map((job) => job.name).join(", ") || "None"}</p><p><span className="text-muted-foreground">Current status:</span> {label(ci.applicability)}</p></div> : <Empty>No GitHub Actions failure has been investigated in this session.</Empty>}</Panel><Panel title="Next safe actions" icon={Activity}>{data.session.repoUrl ? <div className="flex flex-wrap gap-2"><Link className="rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground" to={`/session/${data.session.slugId}/assistant`}>Ask the assistant</Link><Link className="rounded-md border border-border px-3 py-2 text-sm font-medium hover:bg-muted" to={`/session/${data.session.slugId}/knowledge`}>Check knowledge index</Link></div> : <Empty>Connect a repository before beginning a session.</Empty>}</Panel></div></>;
}
function Pipelines({ data }: { data: SingleSessionResponse }) { const s=data.commandCenter; const ci=s?.ci; const ciEvidence=(s?.evidence??[]).filter((e)=>e.sourceType==="ci_log"); return <><PageTitle title="Pipelines" description="Read-only GitHub Actions evidence associated with the selected run. Workflow commands are displayed as repository data and are never executed by Base64." /><div className="grid gap-4 p-6 xl:grid-cols-[minmax(0,1fr)_23rem]"><div className="space-y-4"><Panel title="Run and job status" icon={Workflow}>{ci ? <><div className="mb-4 rounded-lg border border-border bg-muted/25 p-3 text-sm"><p className="font-medium">{ci.workflow_name ?? "GitHub Actions"} · run #{ci.run_id}</p><p className="mt-1 text-muted-foreground">Run SHA <span className="font-mono">{shortSha(ci.head_sha)}</span> · Current SHA <span className="font-mono">{shortSha(ci.current_head_sha)}</span></p></div><div className="flex items-center gap-2 overflow-x-auto py-2">{ci.failed_jobs.map((job,index)=><div key={job.name} className="min-w-44 rounded-lg border border-rose-500/30 bg-rose-500/5 p-3"><p className="font-medium">{job.name}</p><p className="mt-1 text-xs text-muted-foreground">{job.failed_step ?? "Failed job"}</p>{index < ci.failed_jobs.length-1 ? null : null}</div>)}</div><p className="mt-2 text-xs text-muted-foreground">This diagram reflects failed job metadata only; it does not infer unobserved dependency edges.</p></> : <Empty>No selected failed Actions run. Ask “Why did CI fail?” to gather an authorized, read-only CI investigation.</Empty>}</Panel><Panel title="Failure excerpts" icon={AlertTriangle}>{ciEvidence.length ? <div className="space-y-3">{ciEvidence.map((e)=><EvidenceCard key={e.id} item={e}/>)}</div> : <Empty>Logs are not available for this run, or no bounded redacted failure window was retained.</Empty>}</Panel></div><div className="space-y-4"><Panel title="Safety and limits" icon={ShieldCheck}><ul className="space-y-2 text-sm leading-6 text-muted-foreground"><li>• CI logs are untrusted evidence, not instructions.</li><li>• Logs are redacted and bounded before storage or display.</li><li>• Reruns, dispatches, cancellations, and secrets management are not available here.</li></ul></Panel>{ci?.limitations.length ? <Panel title="Limited visibility" icon={AlertTriangle}><ul className="space-y-2 text-sm text-muted-foreground">{ci.limitations.map((x)=><li key={x}>• {x}</li>)}</ul></Panel>:null}</div></div></> }
function Investigation({ data }: { data: SingleSessionResponse }) {const s=data.commandCenter; const i=s?.investigation; return <><PageTitle title="Investigation" description="Structured hypotheses distinguish evidence-supported explanations from symptoms and uncertainty." actions={i ? <Link className="text-sm text-primary hover:underline" to={`/dev/runs/${i.run_id}`}>Open run replay</Link>:null}/><div className="grid gap-4 p-6 xl:grid-cols-[minmax(0,1fr)_23rem]"><Panel title="Diagnosis" icon={FileSearch}>{i?<><Badge variant="outline">{label(i.status)}</Badge><p className="mt-3 leading-7 text-muted-foreground">{i.summary}</p><div className="mt-5 space-y-3">{i.hypotheses.map((h)=><article key={h.id} className="rounded-lg border border-border p-3"><div className="flex flex-wrap justify-between gap-2"><p className="font-medium">{h.title}</p><Badge variant="secondary">{h.status}</Badge></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{h.explanation}</p><p className="mt-2 text-xs text-muted-foreground">Evidence: {h.evidence_ids.length ? h.evidence_ids.join(", ") : "none"}</p></article>)}</div></>:<Empty>No diagnosis has been persisted yet.</Empty>}</Panel><div className="space-y-4"><Panel title="Evidence" icon={BookOpen}>{s?.evidence?.length?<p className="text-sm text-muted-foreground">{s.evidence.length} retained evidence item{s.evidence.length===1?"":"s"} supports this run.</p>:<Empty>No evidence retained.</Empty>}</Panel><Panel title="Limitations" icon={AlertTriangle}>{i?.limitations.length?<ul className="space-y-2 text-sm text-muted-foreground">{i.limitations.map((x)=><li key={x}>• {x}</li>)}</ul>:<p className="text-sm text-muted-foreground">No limitations were recorded.</p>}</Panel></div></div></>}
function Knowledge({ data, slugId }: { data: SingleSessionResponse; slugId: string }) {const qc=useQueryClient(); const mutation=useMutation({mutationFn:()=>reindexSessionRag(slugId),onSuccess:(r)=>{toast.success(r.success?`Indexed ${r.indexed} chunks.`:r.reason??"Index did not complete");qc.invalidateQueries({queryKey:["session",slugId]})},onError:()=>toast.error("Unable to reindex this repository")}); const s=data.commandCenter; return <><PageTitle title="Knowledge" description="Repository retrieval, runbooks, and citations available to evidence-first investigations." actions={<button onClick={()=>mutation.mutate()} disabled={mutation.isPending} className="inline-flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground disabled:opacity-60"><RefreshCw className={cn("size-4",mutation.isPending&&"animate-spin")}/>Reindex repository</button>}/><div className="grid gap-4 p-6 lg:grid-cols-2"><Panel title="Index and repository map" icon={BookOpen}><dl className="space-y-2 text-sm"><div className="flex justify-between"><dt className="text-muted-foreground">Index status</dt><dd>{data.session.indexStatus??"not started"}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">Mapped files</dt><dd>{s?.repository?.file_count??0}</dd></div><div className="flex justify-between"><dt className="text-muted-foreground">CI files</dt><dd>{s?.repository?.ci_files?.length??0}</dd></div></dl></Panel><Panel title="Retrieved sources" icon={FileCode2}>{s?.evidence?.length?<div className="space-y-2">{s.evidence.filter((e)=>e.sourceType!=="ci_log").slice(0,8).map((e)=><EvidenceCard key={e.id} item={e}/>)}</div>:<Empty>Indexing makes repository files and runbooks available for retrieval. It does not automatically grant write access.</Empty>}</Panel></div></>}
function Code({data}:{data:SingleSessionResponse}) {const files=(data.commandCenter?.evidence??[]).filter((e)=>e.path); return <><PageTitle title="Code" description="A safe evidence-focused code surface. File content is shown only when it was retrieved for the selected investigation; no edits are applied from this page."/><div className="grid gap-4 p-6 lg:grid-cols-[16rem_minmax(0,1fr)]"><Panel title="Retrieved files" icon={Code2}>{files.length?<ul className="space-y-2 text-sm">{files.map((f)=><li key={f.id} className="truncate font-mono text-muted-foreground">{f.path}</li>)}</ul>:<Empty>No repository file has been retrieved by this investigation.</Empty>}</Panel><Panel title="Evidence-backed file view" icon={FileCode2}>{files[0]?<><p className="mb-3 font-mono text-sm">{files[0].path}</p><pre className="max-h-[34rem] overflow-auto rounded-lg bg-zinc-950 p-4 text-xs leading-6 text-zinc-100">{files[0].excerpt}</pre><p className="mt-3 text-xs text-muted-foreground">To propose a change, ask the assistant. Any candidate follows validation, deterministic risk classification, exact approval, and delivery controls.</p></>:<Empty>Ask a targeted question to retrieve a file as evidence. The application deliberately does not expose arbitrary browser-side repository writes.</Empty>}</Panel></div></>}
function Changes({data}:{data:SingleSessionResponse}) {const s=data.commandCenter; const p=s?.deliveryPlan; return <><PageTitle title="Changes" description="Every remediation remains a reviewable proposal until its exact plan is approved."/><div className="grid gap-4 p-6 xl:grid-cols-[minmax(0,1fr)_23rem]"><Panel title="Delivery plan" icon={GitPullRequest}>{p?<><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{p.title}</p><Badge variant="outline">{p.risk_level} risk</Badge></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{p.rationale}</p><div className="mt-4 space-y-3">{p.files.map((f)=><article key={f.path} className="rounded-lg border border-border p-3"><p className="font-mono text-sm">{f.path}</p><pre className="mt-2 max-h-64 overflow-auto rounded bg-muted p-3 text-xs">{f.unified_diff}</pre></article>)}</div></>:<Empty>No candidate change exists. An investigation may recommend a remediation without creating an executable patch.</Empty>}</Panel><Panel title="Approval state" icon={ShieldCheck}>{s?.approvals?.length?<div className="space-y-3">{s.approvals.map((a)=><div key={a.id} className="rounded-lg border border-border p-3"><p className="font-medium">{a.summary}</p><p className="mt-1 text-sm text-muted-foreground">{a.status??"pending"} · {a.riskLevel??a.risk}</p></div>)}</div>:<Empty>No approval record. A read-only CI investigation cannot authorize a mutation.</Empty>}</Panel></div></>}
function History({data}:{data:SingleSessionResponse}) {const s=data.commandCenter; return <><PageTitle title="History" description="Persisted run timeline and delivery outcomes. Replay is historical and never re-executes mutations."/><div className="grid gap-4 p-6 lg:grid-cols-2"><Panel title="Run timeline" icon={Clock3}>{s?.timeline?.length?<ol className="space-y-3 border-l border-border pl-4">{s.timeline.map((t)=><li key={t.id}><p className="text-sm font-medium">{t.label??t.name}</p>{t.detail?<p className="text-xs text-muted-foreground">{t.detail}</p>:null}</li>)}</ol>:<Empty>No persisted run timeline yet.</Empty>}</Panel><Panel title="Delivery outcome" icon={GitCommitHorizontal}>{s?.deliveryResult?<div className="space-y-2 text-sm"><p>Status: {s.deliveryResult.status}</p>{s.deliveryResult.commit_sha?<p className="font-mono">{s.deliveryResult.commit_sha}</p>:null}{s.deliveryResult.pull_request_url?<a className="text-primary hover:underline" href={s.deliveryResult.pull_request_url}>Open draft pull request</a>:null}</div>:<Empty>No delivery has been executed for this session.</Empty>}</Panel></div></>}
function SessionPage(){const {slugid,section:rawSection}=useParams(); const section:Section=sections.includes(rawSection as Section)?rawSection as Section:"overview"; const {data,isPending}=useQuery({queryKey:["session",slugid],queryFn:()=>getSessionBySlug(slugid??""),enabled:Boolean(slugid),retry:false}); if(isPending)return <div className="p-6 text-sm text-muted-foreground">Loading session workspace…</div>; if(!data)return <div className="p-6">Session not found.</div>; const props={data}; return <main className="flex h-full min-h-0 w-full flex-col overflow-hidden"><ContextBar data={data}/><div className="min-h-0 flex-1 overflow-y-auto">{section==="overview"?<Overview {...props}/>:section==="assistant"?<div className="h-full min-h-[calc(100dvh-7rem)]"><ChatInterface workspaceMode key={data.session.slugId} initialMessages={data.messages} sessionTitle={data.session.title??"Untitled Session"} slugId={data.session.slugId} repoUrl={data.session.repoUrl??""} defaultBranch={data.session.defaultBranch??"main"} branchName={data.session.branchName} initialCommandCenter={data.commandCenter} initialIndexStatus={data.session.indexStatus} initialIndexError={data.session.indexError}/></div>:section==="pipelines"?<Pipelines {...props}/>:section==="investigation"?<Investigation {...props}/>:section==="knowledge"?<Knowledge {...props} slugId={data.session.slugId}/>:section==="code"?<Code {...props}/>:section==="changes"?<Changes {...props}/>:<History {...props}/>}</div></main>}
export default SessionPage;
